### ISSUE TITLE
Gene Products in GO-CAM browser showing as URIs

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/noctua#706] opened 2021-01-19 23:24 UTC
When looking at the GO-CAM browser (https://geneontology.cloud/browse) for Xenbase models the Gene Products are displayed as URIs rather than gene symbols. In the attached example the gene symbol _rspo2_ is instead replaced by 'http://identifiers.org/xenbase/XB-GENE-946240'. Is this due to some issue in the Xenbase metadata or with the GO-CAM model browser? 
![image](https://user-images.githubusercontent.com/23216004/105104030-898d0900-5a7f-11eb-92c3-c4444b222a95.png)
The gene symbols appear correctly during curation in Noctua so the metadata seems to be available somewhere.

![image](https://user-images.githubusercontent.com/23216004/105105278-cb1eb380-5a81-11eb-8dab-8d784f97b627.png)

This may be a separate issue entirely but just for completeness I'll mention that in the Noctua from editor the MOD specific gene IDs are not live links for Xenbase. Maybe there is some missing connection between Xenbase Gene symbols/IDs and URIs that is affecting both things?

![image](https://user-images.githubusercontent.com/23216004/105106091-6b290c80-5a83-11eb-91cf-67669d674eda.png)

**Comment by balhoff** [comment] 2021-01-20 19:07
I'm guessing this relates to this similar issue: https://github.com/geneontology/web-gocam/issues/14

caused by: https://github.com/geneontology/go-site/issues/1599

**Comment by lpalbou** [comment] 2021-01-27 17:30
@balhoff you are right and this example can help us check when it currently works / not works: https://github.com/geneontology/web-gocam/issues/14#issuecomment-745606791

**Comment by vanaukenk** [comment] 2022-06-08 13:08
Closing for now.  If this problem resurfaces, we can reopen.

**Closed by vanaukenk** 2022-06-08 13:08 UTC

**Comment by malcolmfisher103** [comment] 2022-07-26 14:40
This issue seems to have recurred. It only seems to affect some genes and in some cases both gene symbols and URIs are being shown in the same model.
![image](https://user-images.githubusercontent.com/23216004/181033547-c0e569ee-9a77-4d06-a3dc-60464d19d3b2.png)

The issue may be somewhat different as currently the gene symbols are not showing up in the Noctua lookup.
![image](https://user-images.githubusercontent.com/23216004/181035658-587a64af-e724-40af-aed9-a4f2949ee545.png)
