### ISSUE TITLE
allow editing of annotation

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#300] opened 2016-04-19 22:34 UTC
I added a wrong component in an activity annotation and made already connections and all. Wanted to fix but one can only delete and not add back, this is a major flaw in the box where we can also add extensions.
Thanks! petra

**Comment by kltm** [comment] 2016-04-19 22:37
I believe this is essentially a dupe of #117 .

**Closed by kltm** 2016-04-19 22:37 UTC
