### ISSUE TITLE
Update new Noctua user onboarding form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#642] opened 2020-01-13 15:21 UTC
The current new Noctua user onboarding form needs to be updated to reflect that Noctua is now a production resource.

We'd also like to funnel new submissions through geneontology/helpdesk, if possible, and restrict responses using dropdown menus wherever we can.  This should help with processing the new user data.

Note that we are keeping the form on Google because it allows us to have required fields and create dropdown menus, something we can't currently do with github templates.

Steps:

- [X] Create Google doc for suggested changes to existing form
https://docs.google.com/document/d/1TTXc_HA6KHEHjRhc8VN6yZZYr-ImiY1dlIf8HFCHssI/

- [x] Review and suggest changes to text

- [ ] Identify where dropdown menus could be used and the appropriate source of data

- [ ] Publish new form and link to:
geneontology/helpdesk/issues
Noctua documentation on wiki.geneontology.org

@kltm @suzialeksander @vanaukenk

**Comment by vanaukenk** [comment] 2020-01-13 15:52
@kltm @suzialeksander 
Please see my suggested changes and edits and let me know what you think.

**Comment by kltm** [comment] 2020-01-13 23:31
I've made a pass of my own.

**Comment by vanaukenk** [comment] 2020-05-22 16:22
@kltm @suzialeksander 
Would the two of you have some time next week to go over the new form and see if we can make it public?
I think it is nearly done.
Thx.

**Comment by vanaukenk** [comment] 2022-06-07 13:32
@kltm @suzialeksander - is this (mostly) done?

**Comment by suzialeksander** [comment] 2022-07-26 19:55
I think this is a duplicate of what's active in the New User Onboarding ticket on helpdesk.  Suggest closing.

**Closed** 2023-06-12 23:24 UTC
Labels: high priority, user accounts
