### ISSUE TITLE
gene name labels instead of IDs

### ISSUE THREAD

**Issue by rbalakri** [geneontology/noctua#121] opened 2015-05-13 23:07 UTC
HI,

Can you display the gene name instead of the IDs in each box?

Rama

**Comment by kltm** [comment] 2015-05-13 23:10
This is a feature that will be added later on after the current rewrite. This is a dupe of #48, and possibly some others.

**Closed** 2015-05-13 23:14 UTC
Labels: duplicate

**Comment by cmungall** [comment] 2015-05-14 04:41
If you say so - #48 seems impenetrable to me, I don't see the relevance, and doesn't the label issue belong to @hdietze anyway?

This ticket has a clear and easily testable description so I suggest reopening til it's fixed, as it's high priority. AFAICT it's independent of any refactoring for switching to the individual model.

**Comment by kltm** [comment] 2015-05-14 05:04
@cmungall #48 is now essentially the switch to the newer widget for the autocomplete (courtesy of @jnguyenx) that will supply the label and a better general setup of the additions temples to get rid of acres of duplicate code.
While not strictly related to to the current code push, the code has diverged quite a bit, so we'd have to apply the fix twice if you wanted it before then (going back to a previous point and branching).
