### ISSUE TITLE
When importing an annotation from AmiGO using  a companion / buddy, source providedBy should be retained

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#459] opened 2017-07-06 14:56 UTC
From @vanaukenk's comment here:
https://github.com/geneontology/minerva/issues/119#issuecomment-313402192

This may require dual client and server side coding:

 * [ ] the companion should keep the golr assigned-by value (mapping to prov:providedBy)
 * [ ] minerva should be persuaded not to auto-tag provided by on anything coming from the client. I think the default should be tag with providedBy __iff__ the client does not assign this

**Comment by kltm** [comment] 2017-07-06 15:12
I think this is a dupe of (at least some topics in) #231 , they should be harmonized.

**Comment by cmungall** [comment] 2017-07-11 16:03
Brief summary of skype discussion:

 * We will implement as above (map golr assigned_by to prov:providedBy)
 * More discussion needed on model cloning (should take place in #231)
 * Discussion needed on atomicity of imported triple + evidence unit (but we can proceed independently and just trust curators not to mutate in the interim)

**Comment by cmungall** [comment] 2017-07-11 16:08
I assume this is where we need to add the providedBy:

https://github.com/geneontology/noctua/blob/master/workbenches/companion/Companion.js#L367-L368

**Comment by kltm** [comment] 2017-07-11 16:56
@cmungall No, not really, unless I'm forgetting the API. There needs to be some override mechanism--remember that groups and users are generally added by barista pulling information from the token. In this case, we want to add specific information and make sure that barista understands that it should not override it.
I'll need to check to see if that mechanism is in place and add it if not.

**Comment by kltm** [comment] 2017-10-01 13:32
@cmungall 
Just to clarify this. We currently have two ways to track users/group interactions. I'm a little uncomfortable using providedBy again here--if we have a user, R, doing work for UCL, and copying data in from AmiGO (or TextpressoCentral, or ...), it seems like we'd want to use `dc:source` to distinguish this, as we would otherwise have providedBy: [UCL, <assigned_by>], which may cause issues in untangling work/effort later on.

We discuss this here: https://github.com/geneontology/noctua/issues/231#issuecomment-265627968

**Comment by kltm** [comment] 2017-10-01 13:53
Talking to @cmungall .
For now, we are going to say the providedBy represents the "intellectual work" for a statement. Thus, in many kinds of copy operations, the providedBy will not come from the user's current "hat", but rather something else force selected.
In the case of the buddy import, providedBy will be forced into the manager from the `assigned_by` field.

**Comment by kltm** [comment] 2017-10-01 15:32
@cmungall Ugh.
Okay. Let's say the document we're mapping over from AmiGO has an `assigned_by` of MGI.
What is that? Our providedBys are mercifully URIs right now, so the string isn't going to fly.
If we want this before we have a new field `assigned_by_uri` in AmiGO (take time and plumbing, we'll have to provide our own maps back. That means either a hard-coded map or require a groups.yaml to be fed to all noctua clients. Thoughts?

**Comment by kltm** [comment] 2017-10-01 15:36
Talk with Chris--we'll enforce groups.yaml to have what we want.

**Comment by kltm** [comment] 2017-10-01 16:34
Actually, talking to @cmungall to keep things decoupled right now, well mint our own URLs with "http://purl.obolibrary.org/go/groups/<assigned_by>". This means that GAFs will need to stick to label-strings and be carnality 1, enforcing the earlier conversation about this.

**Closed** 2017-10-02 08:46 UTC
Labels: bug (A: showstopper)
