### ISSUE TITLE
can fill in anything in enabled_by field in "annoton"

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#368] opened 2016-10-24 17:15 UTC
So if you just type in anything without a white space, like "hortence", it does not try to autocomplete (of course, there is nothing called hortence), but you can then fill in MF and CC, and hit "add" and it will give you a box.  This does NOT work if  you use "add individual"; there if try add, you get an error that it does not exist.

Is this a bug in the annoton imput?

**Comment by kltm** [comment] 2016-10-24 23:06
@hdrabkin This is more a quirk in the way that the "Add annoton" interface makes a best effort, while some of the others are a little more strict. This inconsistent behavior will be addressed in items like #261 , #243 , etc.
Essentially, the next UI iteration for the form-like bits should help make that better. If bad data is getting in however, that is something that needs to be addressed.

**Closed by kltm** 2016-10-24 23:06 UTC
Labels: duplicate

**Comment by kltm** [comment] 2016-10-24 23:17
@balhoff 
As well, in some cases, we also explicitly turn off validation so that users can annotate things that are not yet in the system. There are sometimes peripheral issues around this (like https://github.com/geneontology/minerva/issues/53), but we should have some basic sanity checking for this in the near future.

**Comment by hdrabkin** [comment] 2016-10-26 17:12
Yes, that's how I noticed it. We have a Xenbase curator here, and I was demo-ing Noctua.  I didn't expect to be able to enter Xenopus ids, but I could (of course, no autocomplete); then I tried it out with a silly name and it went through.
--
Harold J

**Comment by balhoff** [comment] 2016-10-26 17:15
@hdrabkin did you save the model with the silly name? I believe you should get an error from the backend if you do that.

**Comment by hdrabkin** [comment] 2016-10-26 17:22
No, we did not. We just did Add , looked; were surprised; then just quit.

Again, it would not accept anything if I put it in the "add individual" box. That one required an object from the drop dropdown.

I just tried it now and it allowed a save. See Test Xenopus model

Harold J Drabkin, Ph.D.
Senior Scientific Curator
Mouse Genome Informatics
The Jackson Laboratory
600 Main Street
Bar Harbor, ME 04609
voice:207-288-6650
fax: 207-288-6830
Email: harold.drabkin@jax.org

**Comment by balhoff** [comment] 2016-10-26 17:35
I see!
```
Class: <Horatio>
Class: <XenopusGene>
```
I thought this was no longer possible. Will need to investigate further.

**Comment by kltm** [comment] 2016-10-26 19:54
@balhoff Do you read this as a dupe of geneontology/minerva#53, or as a separate issue?

**Comment by hdrabkin** [comment] 2016-10-27 15:39
On the plus side: it could not resolve a gaf from it.
--
Harold J Drabkin, Ph.D.
Senior Scientific Curator
Mouse Genome Informatics
The Jackson Laboratory
600 Main Street
Bar Harbor, ME 04609
voice:207-288-6650
fax: 207-288-6830
Email: harold.drabkin@jax.org

**Comment by balhoff** [comment] 2016-10-27 17:12
@kltm I thought this was fixed via [minerva #58](https://github.com/geneontology/minerva/issues/58). Has that changed been deployed for Noctua?

**Comment by kltm** [comment] 2016-10-27 20:57
@balhoff Right you are, we're using a Minerva from July right now, but that change got pushed to master 22 days ago.
That said, this is obviously a dupe of that--I'm going to close here.
Everything will be updated momentarily.
