### ISSUE TITLE
saving work

### ISSUE THREAD

**Issue by rbalakri** [geneontology/noctua#124] opened 2015-05-19 18:07 UTC
Hi,

The models shouldn't be autosaved. They should be saved only when we hit the save button. 
Also can there be an undo option?
Thanks,
Rama

**Comment by kltm** [comment] 2015-05-19 19:38
Models are not auto-saved to disk, just the in-memory model in Minerva. Once manually saved, they may be push to cloud storage (i.e. "permanently" saved.) The rest I think folds into #34 and #39, making this a duplicate of the larger question of model handling.
There currently are operations to destroy models by the client, but these are not exposed right now for a lot of good reasons.
There is an undo function per model.

**Closed by kltm** 2015-05-19 19:38 UTC
Labels: duplicate
