### ISSUE TITLE
Improving workflow in "Edit annotations" window

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#439] opened 2017-05-24 17:57 UTC
Many of the things in the Edit Annotations window only allow a single value, that has to be selected from a pull down. It would be really nice if I could just select a new value, instead of having to go through the multistep process:

1. open the menu
2. delete the old value (window closes automatically)
3. open the window again
4. select the new value

It would be a time saver if you could just edit the title box, instead of having to do the same multistep process listed above. Particularly if you want to keep the existing info in the Title, but add a little more, if you forget to copy it before you delete it, it's now gone from the Info listed from the model.

**Comment by krchristie** [comment] 2017-05-24 17:59
Related to the info in the "Edit annotations" window, it would be great if the "Annotation state", i.e. production, development, etc. was listed in the Info tab at the bottom, so I don't even have to open the menu to figure out if I've made it production or not.

**Comment by kltm** [comment] 2017-05-25 00:17
The main body of this issue would seem to be a more-or-less duplicate of https://github.com/geneontology/noctua/issues/117, depending on https://github.com/geneontology/noctua/issues/399.

**Closed by kltm** 2017-05-25 00:17 UTC
