### ISSUE TITLE
ECO:0000315 / IMP annotations not exported to GAF/GPAD?

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#416] opened 2017-04-27 15:24 UTC
Hi,

I created a model and when I export GAF/GPAD, I do not find annotations with ECO:0000315  (mutant phenotype evidence used in manual assertion)

It's this model: http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00002056

Thanks,
Petra

**Comment by balhoff** [comment] 2017-04-27 17:39
Hi @pfey03, I'm not sure what the problem is with the current GPAD export, but I thought you might be interested to take a look at the output from the new GPAD export which is under development:

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/586fc17a00002056.gpad/*view*/

This version makes use of a reasoner and produces more complete results (it does include some annotations with ECO:0000315). I realize this may not be useful to you yet, since it isn't in production, but we're working on finishing it up.

**Comment by kltm** [comment] 2017-04-27 18:34
If the issue is/will be fixed with the new GAF export, besides progressing on the pipeline, is there anything else actionable here?

**Comment by ukemi** [comment] 2017-04-28 14:32
Hi Petra. There are a couple of things going on with this. First, I think we need to take a closer look at your model because there are some things that are missing and may help with the output. The second is that there is a known issue with assigning evidence correctly when models become complex. I don't know whether this is the case here until we revise the model. Would you be willing to either go over the model with us  (@vanaukenk and maybe @thomaspd) on a conference call, or we can go over it with the group on the next annotation call where we discuss a model. 
Another option is that we are proposing to reinstate the noctua-specific calls and we could discuss it  on one of those.

**Comment by pfey03** [comment] 2017-04-28 15:38
Hi David, yes, I would love to go over the model with you and the others, but if it saves time and you prefer, we could use it in the LEGO / annotation call on May 23. I just don't have time to do models often and my problem in general is the mixture of so many relations and possibilities. It's hard to do it correctly and then some bugs to deal with. I only annotated part of the paper in the model, and do have some questions.
If May 23 is too far out, I will move to Madrid this coming Monday for the month of May again. @rjdodson  and I will work together on Thursday, May 4 for the first time. If you have time that Thursday in the early morning or the week after and would like to discuss it before May 23, we could do that. Many thanks!

**Comment by vanaukenk** [comment] 2017-04-28 15:41
Hi - I can do anytime before 11:30am EST on May 4th, if that works for everyone else.
It would be good to also present this on the May23rd call so that we can discuss the model with all of the GO curators, as well.  Thanks, Petra!

**Comment by ukemi** [comment] 2017-04-28 15:47
I am unavailable from 9:30-10:30am EDST on May 4th.

**Comment by pfey03** [comment] 2017-04-28 16:05
@ukemi, would it be too early to do it before 9:30 your Time? Does 8:30 AM EDT work for both of you?

**Comment by ukemi** [comment] 2017-04-28 17:04
8:30 works for me.

**Comment by vanaukenk** [comment] 2017-04-28 17:08
That works for me, too.  I've got it on my calendar.

**Comment by pfey03** [comment] 2017-04-28 17:18
Alright, works for all of us then. Many thanks, you guys are always so helpful - Have a nice weekend!

**Comment by kltm** [comment] 2017-04-28 22:00
Sorry, just looking for clarification here.
- Is this issue still "open"?
- Is this a noctua issue (something wrong with the software) or a model issue (then perhaps https://github.com/geneontology/noctua-models instead)?

**Comment by ukemi** [comment] 2017-04-29 15:47
It is a GPAD generation issue that @balhoff @cmungall @thomaspd and @vanaukenk  and I are already aware of. It is also a model issue. I think we can close it on this tracker.

**Closed** 2017-04-29 21:11 UTC
Labels: invalid

**Comment by cmungall** [comment] 2017-05-05 16:19
We will need to make a noctua ticket since noctua is still redirecting to the old inferences
