### ISSUE TITLE
location of new individuals

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#422] opened 2017-05-08 17:59 UTC
It is annoying and a waste of time when the new individual I have just added or cloned shows up somewhere way off screen and I have to find it and drag it somewhere relevant.

When I duplicate things in other programs, they end up slightly offset from the thing they were cloned from. That seems like a much preferred behavior over ending up somewhere really far away.

**Comment by kltm** [comment] 2017-05-08 19:48
Duplicate of various layout issues:
#173 
#340

**Closed by kltm** 2017-05-08 19:48 UTC
